1
import java.io.FileWriter;

public class Sample{
	public static void main(String[] args) {
		try (FileWriter fw = new FileWriter("data.txt");) {
			fw.write("hello");
		}catch(Exception e) {
			System.out.println("何らかのエラーが発生しました");
		}
	}
}

2
public class Person extends Exception{
	public Person (String msg) {
		super(msg);
	}
}

public class Main {
	public static void main(String[] args) {
		try {
			throw new Person("未対応のファイルです");
		}catch(Exception e) {
			e.printStackTrace();
		}
	}
}

3
public class Main{
	public static void main(String[] args) {
		try {
			String s = null;
			System.out.println(s.length());
		}catch(NullPointerException e) {
			System.out.println("NullPointerException例外をcatchしました");
			System.out.println("--スタックトレース(ここから)--");
			e.printStackTrace();
			System.out.println("--スタックトレース(ここまで)--");
		}
		
	}
}

4
public class Main{
	public static void main(String[] args) {
		try {
			int i = Integer.parseInt("三");
		}catch(NumberFormatException e) {
			System.out.println("error!!!!!!!");
			for(int j = 0; j < 100; j++) {
				System.out.print("-");
			}
			System.out.println();
			e.printStackTrace();
			System.out.println();
			for(int j = 0; j < 100; j++) {
				System.out.print("-");
			}
		}
	}
}

5
import java.io.IOException;

public class Main{
	public static void main(String[] args) throws IOException{
		System.out.println("プログラムが起動しました");
		throw new IOException();
	}
}
